// Handles follow-up action buttons embedded in SF chat messages.
// Buttons are generated by buildChatContent (chat-output.js) with class
// .gdsa-followup-btn and data-action / data-params attributes.
//
// Supported actions:
//   enemy-pa         — selected target rolls a PA
//   enemy-stat       — selected target rolls a stat check via GDSA dialog
//   hero-se          — speaker rolls Selbstbeherrschung via GDSA talent dialog
//   hero-stat        — speaker rolls a stat check via GDSA dialog
//   hero-talent-probe — speaker rolls any talent via GDSA talent dialog

import { rollD20Defense } from "./roll-engine.js";
import { buildChatContent, postChatMessage } from "./chat-output.js";
import { getFirstTarget, applyAndReport } from "./target-effects.js";
import { applyStatusEffect, applyStatusEffectRoll } from "./status-effects.js";

// Returns true if the actor has the Tollpatsch disadvantage.
// Mirrors the detection used by GDSA's own sheet getData() logic.
function _isGoofy(actor) {
    if (!actor) return false;
    const localName = game.i18n?.localize("GDSA.flaws.goofy") ?? "Tollpatsch";
    return actor.items?.some(i =>
        i.type === "Template" && (i.name === localName || i.name === "Tollpatsch")
    ) ?? false;
}

// ─── GDSA module cache ────────────────────────────────────────────────────────

let _gdsa = null;
async function _loadGDSA() {
    if (_gdsa) return _gdsa;
    const [Dialog, Dice] = await Promise.all([
        import("/systems/gdsa/module/dialog.js"),
        import("/systems/gdsa/module/dice.js"),
    ]);
    _gdsa = { Dialog, Dice };
    return _gdsa;
}

// ─── Dialog pre-fill helper ───────────────────────────────────────────────────

// Registers a persistent renderDialog hook that sets input[name='disadvantage']
// to `n` on the first matching dialog (one that has this field), then removes itself.
function _prefillDisadvantage(n) {
    if (!n) return;
    let hookId;
    hookId = Hooks.on("renderDialog", (_dlg, html) => {
        const field = html[0].querySelector("input[name='disadvantage']");
        if (!field) return;               // not a skill/stat dialog — keep listening
        Hooks.off("renderDialog", hookId); // found it — unregister
        field.value = String(n);
        field.dispatchEvent(new Event("input",  { bubbles: true }));
        field.dispatchEvent(new Event("change", { bubbles: true }));
    });
}

// ─── Actor helpers ────────────────────────────────────────────────────────────

function _pa(actor, skill) {
    const skillEntry = actor.system.skill?.[skill];
    if (skillEntry !== undefined) {
        const def = parseInt(skillEntry.def);
        if (Number.isFinite(def) && def > 0) return def;
    }
    return parseInt(actor.system?.mainPA)
        || parseInt(actor.system?.PABasis?.value)
        || parseInt(actor.system?.PA?.value)
        || 8;
}

function _stat(actor, key) {
    return parseInt(
        actor.system[key]?.value
        ?? actor.system[key?.toLowerCase()]?.value
        ?? actor.system[key]
        ?? actor.system[key?.toLowerCase()]
    ) || 10;
}

function _hasSF(actor, name) {
    return actor.items.some(i =>
        i.type === "Template" && i.system?.type === "trai" && i.name === name
    );
}

// ─── Action handlers ──────────────────────────────────────────────────────────

async function _enemyPA(params) {
    const target = getFirstTarget();
    if (!target) { ui.notifications.warn("Kein Ziel ausgewählt."); return; }
    const tActor = target.actor ?? target.document?.actor;
    if (!tActor) { ui.notifications.warn("Ziel-Charakter nicht gefunden."); return; }

    const modifier = params.modifier ?? 0;
    const label    = params.skill;
    const pa       = _pa(tActor, label);
    const paResult = await rollD20Defense(pa, modifier, label, tActor);
    const modStr   = modifier ? ` (${modifier > 0 ? "+" : ""}${modifier})` : "";
    const notes = [];
    if ((paResult.blocked || paResult.crit) && params.successNote) notes.push(params.successNote);
    if (!(paResult.blocked || paResult.crit) && params.failNote)    notes.push(params.failNote);

    await postChatMessage(tActor, buildChatContent({
        sfName: `Parade: ${label}${modStr}`, skill: label, paResult, notes,
    }));
}

// Triggers the GDSA stat-check dialog for `actor`, pre-filling the disadvantage field.
// On confirm, runs Dice.statCheck with the GDSA native chat template.
async function _gdsaStatProbe(actor, params) {
    const statKey  = params.stat;
    const statName = params.statName ?? statKey;
    const statObj  = actor.system[statKey] ?? actor.system[statKey?.toLowerCase()] ?? {};
    const statVal  = parseInt(statObj.value) || 10;
    const statMod  = statKey !== "MR" ? (parseInt(statObj.temp) || 0) : 0;
    const sys      = actor.system;

    const statInfo = {
        name:      statName,
        klerikal:  sys.klerikal ?? false,
        isTalentS: (parseInt(sys.skill?.["Kräfteschub [" + statName + "]"]) || 0) > 0,
        isMR:      statKey === "MR",
        ironWill:  _hasSF(actor, "Eiserner Wille I") || _hasSF(actor, "Eiserner Wille II"),
        willProt:  _hasSF(actor, "Gedankenschutz"),
    };

    _prefillDisadvantage(params.disadvantage ?? (params.modifier < 0 ? -params.modifier : 0));

    const { Dialog, Dice } = await _loadGDSA();
    const opts = await Dialog.GetStatCheckOptions(statInfo);
    if (opts.cancelled) return null;

    const modif = parseInt(opts.advantage || 0) - parseInt(opts.disadvantage || 0)
        - (parseInt(sys.simpleCheckPen) || 0);

    const result = await Dice.statCheck(statName, statVal, statMod, actor, modif, {});

    const note = result?.succ ? params.successNote : params.failNote;
    if (note) {
        await postChatMessage(actor, buildChatContent({ sfName: statName, skill: null, notes: [note] }));
    }

    // Apply Erschöpfung on success if configured (e.g. Verbotene Pforten: 1)
    if (result?.succ && params.erschoepfung) {
        await applyStatusEffect(actor, "Erschöpfung", params.erschoepfung);
    }

    return result;
}

// Triggers the GDSA talent-check dialog for `actor`, pre-filling the disadvantage field.
// On confirm, runs Dice.skillCheck with the GDSA native chat template.
async function _gdsaTalentProbe(actor, params) {
    const talentName   = params.talentName ?? "Selbstbeherrschung";
    const disadvantage = params.disadvantage ?? 0;

    const talentTemplate = CONFIG.Templates?.talents?.all?.find(t => t.name === talentName);
    if (!talentTemplate) {
        ui.notifications.warn(`Talent-Vorlage '${talentName}' nicht in CONFIG.Templates gefunden.`);
        return null;
    }

    const tale = talentTemplate.system?.tale ?? {};
    const taw  = parseInt(actor.system.skill?.[talentName]) || 0;
    const sys  = actor.system;

    // BE disadvantage (same logic as GDSA doSkillRoll)
    let beDis = 0;
    if (tale.BECheck) {
        const be = parseInt(sys.gBEArmour) || 0;
        if (tale.BEtype === "x") beDis = be * (tale.BE ?? 0);
        else if (tale.BEtype === "-" && be > (tale.BE ?? 0)) beDis = be - (tale.BE ?? 0);
        if (beDis < 0) beDis = 0;
    }

    // Build the skill info object the GDSA dialog template expects
    const skillForDialog = Object.assign({}, talentTemplate, {
        isMHK:    false,
        MHKMx:    Math.round(taw / 2),
        beDis,
        klerikal: sys.klerikal ?? false,
        isTalentS: (parseInt(sys.skill?.["Talentschub" + talentName]) || 0) > 0,
    });

    _prefillDisadvantage(disadvantage);

    const { Dialog, Dice } = await _loadGDSA();
    const opts = await Dialog.GetSkillCheckOptions(skillForDialog);
    if (opts.cancelled) return null;

    const att1 = (tale.att1 ?? "mu").toUpperCase();
    const att2 = (tale.att2 ?? "mu").toUpperCase();
    const att3 = (tale.att3 ?? "ko").toUpperCase();
    const getAtt = n => (parseInt(sys[n]?.value) || 0) + (parseInt(sys[n]?.temp) || 0);

    const modif = parseInt(opts.advantage || 0) - parseInt(opts.disadvantage || 0)
        - (opts.be ? beDis : 0)
        - (parseInt(sys.fullCheckPen) || 0);

    const optional = {
        template: "systems/gdsa/templates/chat/chatTemplate/skill-Roll.hbs",
        item: talentTemplate,
        att1, att2, att3,
        noChat: false,
        used:   [],
        mhk:    false,
        asp:    0,
    };

    const result = await Dice.skillCheck(
        talentName, taw,
        getAtt(att1), getAtt(att2), getAtt(att3),
        actor,          // actual Actor doc — works with ChatMessage.getSpeaker
        _isGoofy(actor), // Tollpatsch: 2× (19 or 20) = Patzer bei 3W20
        modif,
        optional
    );

    const note = result?.succ ? params.successNote : params.failNote;
    if (note) {
        await postChatMessage(actor, buildChatContent({ sfName: talentName, skill: null, notes: [note] }));
    }

    // Apply Erschöpfung on success if configured (e.g. Verbotene Pforten: 1)
    if (result?.succ && params.erschoepfung) {
        await applyStatusEffect(actor, "Erschöpfung", params.erschoepfung);
    }

    return result;
}

// ─── Public action dispatchers ────────────────────────────────────────────────

async function _enemyStat(params, message) {
    const target = getFirstTarget();
    if (!target) { ui.notifications.warn("Kein Ziel ausgewählt."); return; }
    const tActor = target.actor ?? target.document?.actor;
    if (!tActor) { ui.notifications.warn("Ziel-Charakter nicht gefunden."); return; }

    const result = await _gdsaStatProbe(tActor, params);
    if (!result) return;

    // Apply on-fail effects if configured (e.g. prone, INI loss)
    if (!result.succ && params.onFail) {
        const ef = params.onFail;
        const appliedEffects = {};
        if (ef.iniLossFormula) appliedEffects.iniLossFormula = ef.iniLossFormula;
        if (ef.prone)          appliedEffects.prone = true;
        if (Object.keys(appliedEffects).length) {
            const notes = await applyAndReport(null, target, appliedEffects);
            if (notes.length) {
                await postChatMessage(tActor, buildChatContent({
                    sfName: params.statName ?? params.stat, skill: null, notes,
                }));
            }
        }
    }
}

async function _heroSE(params, message) {
    const actor = game.actors?.get(message.speaker?.actor ?? "");
    if (!actor) { ui.notifications.warn("Sprecher-Charakter nicht gefunden."); return; }
    // SE = Selbstbeherrschung is a talent → use talent probe dialog
    await _gdsaTalentProbe(actor, {
        talentName:   "Selbstbeherrschung",
        disadvantage: params.modifier > 0 ? params.modifier : 0,
        successNote:  params.successNote,
        failNote:     params.failNote,
    });
}

async function _heroStat(params, message) {
    const actor = game.actors?.get(message.speaker?.actor ?? "");
    if (!actor) { ui.notifications.warn("Sprecher-Charakter nicht gefunden."); return; }
    await _gdsaStatProbe(actor, params);
}

async function _heroTalentProbe(params, message) {
    const actor = game.actors?.get(message.speaker?.actor ?? "");
    if (!actor) { ui.notifications.warn("Sprecher-Charakter nicht gefunden."); return; }
    await _gdsaTalentProbe(actor, params);
}

// ─── Mondsüchtig probe ───────────────────────────────────────────────────────

async function _showMoonPhaseDialog() {
    return new Promise(resolve => {
        new Dialog({
            title: "Mondsüchtig: Mondphase",
            content: `<form style="padding:4px 0">
                <div class="form-group">
                    <label style="font-weight:bold">Aktuelle Mondphase:</label>
                    <select name="phase" style="width:100%;margin-top:6px">
                        <option value="0">Tote Mada — kein Effekt</option>
                        <option value="1">Zunehmende Mada — +1 Verzückung</option>
                        <option value="2">Helm — +2 Verzückung</option>
                        <option value="4">Rad — +4 Verzückung</option>
                    </select>
                </div>
            </form>`,
            buttons: {
                ok:     { label: "Anwenden", callback: html => resolve(parseInt(html[0].querySelector("[name=phase]").value) || 0) },
                cancel: { label: "Abbrechen", callback: () => resolve(null) },
            },
            default: "ok",
        }).render(true);
    });
}

async function _mondsuechtigProbe(params, message) {
    const actor = game.actors?.get(message.speaker?.actor ?? "");
    if (!actor) { ui.notifications.warn("Sprecher-Charakter nicht gefunden."); return; }

    const result = await _gdsaTalentProbe(actor, {
        talentName:  "Selbstbeherrschung",
        successNote: "SE-Probe bestanden — kein Mondwahn.",
    });
    if (!result) return;

    if (!result.succ) {
        const points = await _showMoonPhaseDialog();
        if (points === null) return;
        if (points === 0) {
            ChatMessage.create({
                content: `<div class="gdsa-sf-notes"><div class="gdsa-sf-note">🌑 ${actor.name}: Tote Mada — kein Verzückungseffekt.</div></div>`,
                speaker: ChatMessage.getSpeaker({ actor }),
            });
        } else {
            await applyStatusEffect(actor, "Verzückung", points);
            ChatMessage.create({
                content: `<div class="gdsa-sf-notes"><div class="gdsa-sf-note">🌕 ${actor.name}: Mondsüchtig — +${points} Verzückung (−${points} auf alle Proben).</div></div>`,
                speaker: ChatMessage.getSpeaker({ actor }),
            });
        }
    }
}

// ─── Hook ────────────────────────────────────────────────────────────────────

export function registerFollowUpHook() {
    Hooks.on("renderChatMessage", (message, html, _data) => {
        const buttons = html[0].querySelectorAll(".gdsa-followup-btn");
        if (!buttons.length) return;

        for (const btn of buttons) {
            btn.addEventListener("click", async e => {
                e.preventDefault();
                e.stopPropagation();
                const action = btn.dataset.action ?? "";
                let params = {};
                try { params = JSON.parse(btn.dataset.params ?? "{}"); } catch { /**/ }

                switch (action) {
                    case "enemy-pa":           await _enemyPA(params);                     break;
                    case "enemy-stat":         await _enemyStat(params, message);           break;
                    case "hero-se":            await _heroSE(params, message);              break;
                    case "hero-stat":          await _heroStat(params, message);            break;
                    case "hero-talent-probe":  await _heroTalentProbe(params, message);     break;
                    case "mondsuechtig-probe": await _mondsuechtigProbe(params, message);   break;
                }
            });
        }
    });
}
